/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Produto;
import java.util.ArrayList;

/**
 *
 * @author Felipe
 */
public class GuiProduto extends javax.swing.JFrame {

    /**
     * Creates new form GuiProduto
     */
    public GuiProduto(ArrayList<Produto> p) {
        initComponents();
        cadProd = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPrecoUnit = new javax.swing.JTextField();
        jTextFieldEstqMin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jTextFieldQtdDisp = new javax.swing.JTextField();
        jButtonSair = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonIncluir = new javax.swing.JButton();
        jButtonConsult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Produto");
        setName("GuiProduto"); // NOI18N

        jTextFieldPrecoUnit.setEnabled(false);

        jTextFieldEstqMin.setEnabled(false);

        jLabel1.setText("Código");

        jLabel2.setText("Descrição");

        jLabel3.setText("Qtde Disponivel");

        jLabel4.setText("Preço Unit");

        jLabel5.setText("Estq Min");

        jTextFieldDescricao.setEnabled(false);

        jTextFieldQtdDisp.setEnabled(false);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        jButtonIncluir.setText("Incluir");
        jButtonIncluir.setEnabled(false);
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonConsult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        jButtonConsult.setText("Consultar");
        jButtonConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDescricao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(jTextFieldQtdDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPrecoUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEstqMin))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonConsult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jButtonIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldQtdDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecoUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEstqMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsult)
                    .addComponent(jButtonSair)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonIncluir))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultActionPerformed
        int x;
        for (x = 0; x <  cadProd.size(); x++)
        {
            if( cadProd.get(x) instanceof Produto)
            {
                if (((Produto)cadProd.get(x)).getCodigo().equals(jTextFieldCodigo.getText()))
                {
                    break;
                }
            }      
        }
        if(x < cadProd.size())
        {
         posProduto = x;
        }
        else
        {
         posProduto = -1;
        
        }
        if(posProduto >= 0)
        {
            jTextFieldCodigo.setText((String) cadProd.get(posProduto).getCodigo());
            jTextFieldDescricao.setText(cadProd.get(posProduto).getDescricao());
            jTextFieldQtdDisp.setText(String.valueOf(cadProd.get(posProduto).getQtdeEstoque()));
            jTextFieldPrecoUnit.setText(String.valueOf(cadProd.get(posProduto).getPreco()));
            jTextFieldEstqMin.setText(String.valueOf(cadProd.get(posProduto).getEstoqueMinimo()));
        
            jButtonConsult.setEnabled(false);
            jButtonIncluir.setEnabled(false);
            jButtonAlterar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
        }
        else
        {
            jButtonConsult.setEnabled(false);
            jButtonIncluir.setEnabled(true);
            jButtonAlterar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jTextFieldDescricao.requestFocus();
        }
        
        jTextFieldCodigo.setEnabled(false);
        jTextFieldDescricao.setEnabled(true);
        jTextFieldQtdDisp.setEnabled(true);
        jTextFieldPrecoUnit.setEnabled(true);
        jTextFieldEstqMin.setEnabled(true);
    }//GEN-LAST:event_jButtonConsultActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        Produto prod = new Produto(jTextFieldCodigo.getText(), 
                               jTextFieldDescricao.getText()); 
                               prod.setQtdeEstoque(Double.parseDouble(jTextFieldQtdDisp.getText()));
                               prod.setPreco(Double.parseDouble(jTextFieldPrecoUnit.getText()));
                               prod.setEstoqueMinimo(Double.parseDouble(jTextFieldEstqMin.getText()));                                
                              
                               
        cadProd.add(prod);        
        
        jTextFieldCodigo.setText(null);
        jTextFieldDescricao.setText(null);
        jTextFieldQtdDisp.setText(null);
        jTextFieldPrecoUnit.setText(null);
        jTextFieldEstqMin.setText(null);
        jButtonConsult.setEnabled(true);
        jButtonIncluir.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextFieldCodigo.setEnabled(true);
        jTextFieldDescricao.setEnabled(false);
        jTextFieldQtdDisp.setEnabled(false);
        jTextFieldPrecoUnit.setEnabled(false);
        jTextFieldEstqMin.setEnabled(false); 
        jTextFieldCodigo.requestFocus();
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        jTextFieldCodigo.setEnabled(false);
        cadProd.get(posProduto).setDescricao(jTextFieldDescricao.getText());
        ((Produto)cadProd.get(posProduto)).setQtdeEstoque(Double.parseDouble(jTextFieldQtdDisp.getText()));
        ((Produto)cadProd.get(posProduto)).setPreco(Double.parseDouble(jTextFieldPrecoUnit.getText()));
        ((Produto)cadProd.get(posProduto)).setEstoqueMinimo(Double.parseDouble(jTextFieldEstqMin.getText()));
                
        jTextFieldCodigo.setText(null);
        jTextFieldDescricao.setText(null);
        jTextFieldQtdDisp.setText(null);
        jTextFieldPrecoUnit.setText(null);
        jTextFieldEstqMin.setText(null);
        jButtonConsult.setEnabled(true);
        jButtonIncluir.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);        
        jTextFieldCodigo.setEnabled(true);
        jTextFieldDescricao.setEnabled(false);
        jTextFieldQtdDisp.setEnabled(false);
        jTextFieldPrecoUnit.setEnabled(false);
        jTextFieldEstqMin.setEnabled(false); 
        jTextFieldCodigo.requestFocus();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (posProduto >= 0)
        {
            cadProd.remove(posProduto);
            posProduto = -1;
        }
        
        jTextFieldCodigo.setText(null);
        jTextFieldDescricao.setText(null);
        jTextFieldQtdDisp.setText(null);
        jTextFieldPrecoUnit.setText(null);
        jTextFieldEstqMin.setText(null);
        jButtonConsult.setEnabled(true);
        jButtonIncluir.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);        
        jTextFieldCodigo.setEnabled(true);
        jTextFieldDescricao.setEnabled(false);
        jTextFieldQtdDisp.setEnabled(false);
        jTextFieldPrecoUnit.setEnabled(false);
        jTextFieldEstqMin.setEnabled(false); 
        jTextFieldCodigo.requestFocus();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GuiProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonConsult;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldEstqMin;
    private javax.swing.JTextField jTextFieldPrecoUnit;
    private javax.swing.JTextField jTextFieldQtdDisp;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Produto> cadProd;
    private int posProduto;
}
